daana_user_landing:
    pattern: /
    defaults: { _controller: DaanaUserBundle:Default:index }

daana_login_submit:
    pattern: /login_submit
    defaults: { _controller: DaanaUserBundle:Default:loginSubmit }
